### PR TITLE
Make the kernel actually do something useful. :)

### PR DESCRIPTION
**Pull request by jeffallen**

### CODE REVIEW

**Comment by lloydjatkinson** [comment]
I wonder if the author is regretting the recent wave of attention yet.

**Comment by cristim** [comment]
Please fix the TravisCI build:

```
[gometalinter] linting sources
kernel/kmain/nyan.go:52:1:warning: exported function Nyan should have comment or be unexported (golint)
make: *** [lint] Error 1
```

**Comment by cristim** [comment]
@jefallen you can update this PR, no need to create a new one for the same thing.

**Comment by jeffallen** [comment]
I was dissatisfied with the commit history, because the Github editor put an incorrect message onto edits I made.

**Pull request closed without merging**
